# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    #Task To build the image using docker file
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/sampleapp/Dockerfile'
        tags: |
          $(tag)
     #  Task to build the image and push the image to azure container registry (acr) using the already created service connection named  servconnacr which connects devops to docker hub  
    - task: Docker@2
      inputs:
        containerRegistry: 'servconnacr'
        repository: 'seethal/samplekubernetes'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
      #  Task to build the image and pushthe imageto my private docker hub using the already created service connection named  dockerserviceconnection which connects devops to acr server  
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerserviceconnection'
        repository: 'seethal1/samplekubernetes'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    # This is to publish build artifacts so that we can copy the deployment.yaml file (later) which contains the code to deploy to Azure Kubernetes Service    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        #This is to copy the all .yaml files (build artifactss) to artifacts
    - task: CopyPublishBuildArtifacts@1
      inputs:
        Contents: '*.yaml'
        ArtifactName: 'yamlartifacts'
        ArtifactType: 'Container'
